// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verifier/verifier.proto

package verifier

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MakeCredentialRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AkName               string   `protobuf:"bytes,2,opt,name=akName,proto3" json:"akName,omitempty"`
	EkPub                []byte   `protobuf:"bytes,3,opt,name=ekPub,proto3" json:"ekPub,omitempty"`
	AkPub                []byte   `protobuf:"bytes,4,opt,name=akPub,proto3" json:"akPub,omitempty"`
	AkPubCert            []byte   `protobuf:"bytes,5,opt,name=akPubCert,proto3" json:"akPubCert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeCredentialRequest) Reset()         { *m = MakeCredentialRequest{} }
func (m *MakeCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*MakeCredentialRequest) ProtoMessage()    {}
func (*MakeCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{0}
}

func (m *MakeCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeCredentialRequest.Unmarshal(m, b)
}
func (m *MakeCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeCredentialRequest.Marshal(b, m, deterministic)
}
func (m *MakeCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeCredentialRequest.Merge(m, src)
}
func (m *MakeCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_MakeCredentialRequest.Size(m)
}
func (m *MakeCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeCredentialRequest proto.InternalMessageInfo

func (m *MakeCredentialRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *MakeCredentialRequest) GetAkName() string {
	if m != nil {
		return m.AkName
	}
	return ""
}

func (m *MakeCredentialRequest) GetEkPub() []byte {
	if m != nil {
		return m.EkPub
	}
	return nil
}

func (m *MakeCredentialRequest) GetAkPub() []byte {
	if m != nil {
		return m.AkPub
	}
	return nil
}

func (m *MakeCredentialRequest) GetAkPubCert() []byte {
	if m != nil {
		return m.AkPubCert
	}
	return nil
}

type MakeCredentialResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pcr                  int32    `protobuf:"varint,2,opt,name=pcr,proto3" json:"pcr,omitempty"`
	CredBlob             []byte   `protobuf:"bytes,3,opt,name=credBlob,proto3" json:"credBlob,omitempty"`
	EncryptedSecret      []byte   `protobuf:"bytes,4,opt,name=encryptedSecret,proto3" json:"encryptedSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeCredentialResponse) Reset()         { *m = MakeCredentialResponse{} }
func (m *MakeCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*MakeCredentialResponse) ProtoMessage()    {}
func (*MakeCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{1}
}

func (m *MakeCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeCredentialResponse.Unmarshal(m, b)
}
func (m *MakeCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeCredentialResponse.Marshal(b, m, deterministic)
}
func (m *MakeCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeCredentialResponse.Merge(m, src)
}
func (m *MakeCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_MakeCredentialResponse.Size(m)
}
func (m *MakeCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeCredentialResponse proto.InternalMessageInfo

func (m *MakeCredentialResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *MakeCredentialResponse) GetPcr() int32 {
	if m != nil {
		return m.Pcr
	}
	return 0
}

func (m *MakeCredentialResponse) GetCredBlob() []byte {
	if m != nil {
		return m.CredBlob
	}
	return nil
}

func (m *MakeCredentialResponse) GetEncryptedSecret() []byte {
	if m != nil {
		return m.EncryptedSecret
	}
	return nil
}

type ActivateCredentialRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Attestation          []byte   `protobuf:"bytes,3,opt,name=attestation,proto3" json:"attestation,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateCredentialRequest) Reset()         { *m = ActivateCredentialRequest{} }
func (m *ActivateCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateCredentialRequest) ProtoMessage()    {}
func (*ActivateCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{2}
}

func (m *ActivateCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateCredentialRequest.Unmarshal(m, b)
}
func (m *ActivateCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateCredentialRequest.Marshal(b, m, deterministic)
}
func (m *ActivateCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateCredentialRequest.Merge(m, src)
}
func (m *ActivateCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateCredentialRequest.Size(m)
}
func (m *ActivateCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateCredentialRequest proto.InternalMessageInfo

func (m *ActivateCredentialRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ActivateCredentialRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ActivateCredentialRequest) GetAttestation() []byte {
	if m != nil {
		return m.Attestation
	}
	return nil
}

func (m *ActivateCredentialRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ActivateCredentialResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Verified             bool     `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	ImportBlob           []byte   `protobuf:"bytes,3,opt,name=importBlob,proto3" json:"importBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateCredentialResponse) Reset()         { *m = ActivateCredentialResponse{} }
func (m *ActivateCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateCredentialResponse) ProtoMessage()    {}
func (*ActivateCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{3}
}

func (m *ActivateCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateCredentialResponse.Unmarshal(m, b)
}
func (m *ActivateCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateCredentialResponse.Marshal(b, m, deterministic)
}
func (m *ActivateCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateCredentialResponse.Merge(m, src)
}
func (m *ActivateCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateCredentialResponse.Size(m)
}
func (m *ActivateCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateCredentialResponse proto.InternalMessageInfo

func (m *ActivateCredentialResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ActivateCredentialResponse) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *ActivateCredentialResponse) GetImportBlob() []byte {
	if m != nil {
		return m.ImportBlob
	}
	return nil
}

type OfferQuoteRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferQuoteRequest) Reset()         { *m = OfferQuoteRequest{} }
func (m *OfferQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*OfferQuoteRequest) ProtoMessage()    {}
func (*OfferQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{4}
}

func (m *OfferQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferQuoteRequest.Unmarshal(m, b)
}
func (m *OfferQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferQuoteRequest.Marshal(b, m, deterministic)
}
func (m *OfferQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferQuoteRequest.Merge(m, src)
}
func (m *OfferQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_OfferQuoteRequest.Size(m)
}
func (m *OfferQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OfferQuoteRequest proto.InternalMessageInfo

func (m *OfferQuoteRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type OfferQuoteResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pcr                  int32    `protobuf:"varint,2,opt,name=pcr,proto3" json:"pcr,omitempty"`
	Nonce                string   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferQuoteResponse) Reset()         { *m = OfferQuoteResponse{} }
func (m *OfferQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*OfferQuoteResponse) ProtoMessage()    {}
func (*OfferQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{5}
}

func (m *OfferQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferQuoteResponse.Unmarshal(m, b)
}
func (m *OfferQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferQuoteResponse.Marshal(b, m, deterministic)
}
func (m *OfferQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferQuoteResponse.Merge(m, src)
}
func (m *OfferQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_OfferQuoteResponse.Size(m)
}
func (m *OfferQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OfferQuoteResponse proto.InternalMessageInfo

func (m *OfferQuoteResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OfferQuoteResponse) GetPcr() int32 {
	if m != nil {
		return m.Pcr
	}
	return 0
}

func (m *OfferQuoteResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type ProvideQuoteRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Attestation          []byte   `protobuf:"bytes,3,opt,name=attestation,proto3" json:"attestation,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvideQuoteRequest) Reset()         { *m = ProvideQuoteRequest{} }
func (m *ProvideQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*ProvideQuoteRequest) ProtoMessage()    {}
func (*ProvideQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{6}
}

func (m *ProvideQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideQuoteRequest.Unmarshal(m, b)
}
func (m *ProvideQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideQuoteRequest.Marshal(b, m, deterministic)
}
func (m *ProvideQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideQuoteRequest.Merge(m, src)
}
func (m *ProvideQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_ProvideQuoteRequest.Size(m)
}
func (m *ProvideQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideQuoteRequest proto.InternalMessageInfo

func (m *ProvideQuoteRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProvideQuoteRequest) GetAttestation() []byte {
	if m != nil {
		return m.Attestation
	}
	return nil
}

func (m *ProvideQuoteRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ProvideQuoteResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Verified             bool     `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvideQuoteResponse) Reset()         { *m = ProvideQuoteResponse{} }
func (m *ProvideQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*ProvideQuoteResponse) ProtoMessage()    {}
func (*ProvideQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc12b0604e249fd5, []int{7}
}

func (m *ProvideQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideQuoteResponse.Unmarshal(m, b)
}
func (m *ProvideQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideQuoteResponse.Marshal(b, m, deterministic)
}
func (m *ProvideQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideQuoteResponse.Merge(m, src)
}
func (m *ProvideQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_ProvideQuoteResponse.Size(m)
}
func (m *ProvideQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideQuoteResponse proto.InternalMessageInfo

func (m *ProvideQuoteResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProvideQuoteResponse) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func init() {
	proto.RegisterType((*MakeCredentialRequest)(nil), "verifier.MakeCredentialRequest")
	proto.RegisterType((*MakeCredentialResponse)(nil), "verifier.MakeCredentialResponse")
	proto.RegisterType((*ActivateCredentialRequest)(nil), "verifier.ActivateCredentialRequest")
	proto.RegisterType((*ActivateCredentialResponse)(nil), "verifier.ActivateCredentialResponse")
	proto.RegisterType((*OfferQuoteRequest)(nil), "verifier.OfferQuoteRequest")
	proto.RegisterType((*OfferQuoteResponse)(nil), "verifier.OfferQuoteResponse")
	proto.RegisterType((*ProvideQuoteRequest)(nil), "verifier.ProvideQuoteRequest")
	proto.RegisterType((*ProvideQuoteResponse)(nil), "verifier.ProvideQuoteResponse")
}

func init() {
	proto.RegisterFile("verifier/verifier.proto", fileDescriptor_cc12b0604e249fd5)
}

var fileDescriptor_cc12b0604e249fd5 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x0d, 0xae, 0x9c, 0xa1, 0x82, 0x32, 0x84, 0x62, 0x4c, 0x29, 0xd6, 0x02, 0x52, 0x4e,
	0x45, 0x82, 0x5f, 0x00, 0xe5, 0xc2, 0x81, 0x26, 0x18, 0xc1, 0x7d, 0x63, 0x4f, 0xa2, 0x25, 0x89,
	0xd7, 0xac, 0xd7, 0x91, 0xb8, 0x22, 0x71, 0xe2, 0x4f, 0xf2, 0x53, 0x90, 0xd7, 0x9f, 0x49, 0xec,
	0x88, 0x8f, 0xdb, 0xbc, 0xb7, 0xb3, 0x3b, 0xcf, 0x6f, 0x66, 0x0c, 0x0f, 0x36, 0xa4, 0xc4, 0x5c,
	0x90, 0x7a, 0x51, 0x05, 0x97, 0x89, 0x92, 0x5a, 0xa2, 0x53, 0x61, 0xf6, 0xd3, 0x82, 0xfb, 0xef,
	0xf9, 0x92, 0xae, 0x14, 0x45, 0x14, 0x6b, 0xc1, 0x57, 0x01, 0x7d, 0xcd, 0x28, 0xd5, 0x78, 0x0a,
	0x83, 0x4c, 0x44, 0xae, 0xe5, 0x5b, 0xe3, 0x61, 0x90, 0x87, 0x78, 0x06, 0xc7, 0x7c, 0x79, 0xcd,
	0xd7, 0xe4, 0x1e, 0x19, 0xb2, 0x44, 0x38, 0x02, 0x9b, 0x96, 0xd3, 0x6c, 0xe6, 0x0e, 0x7c, 0x6b,
	0x7c, 0x12, 0x14, 0x20, 0x67, 0xb9, 0x61, 0x6f, 0x16, 0xac, 0x01, 0x78, 0x0e, 0x43, 0x13, 0x5c,
	0x91, 0xd2, 0xae, 0x6d, 0x4e, 0x1a, 0x82, 0x7d, 0xb7, 0xe0, 0x6c, 0x57, 0x4d, 0x9a, 0xc8, 0x38,
	0xa5, 0x0e, 0x39, 0xa7, 0x30, 0x48, 0x42, 0x65, 0xb4, 0xd8, 0x41, 0x1e, 0xa2, 0x07, 0x4e, 0xa8,
	0x28, 0x7a, 0xb3, 0x92, 0x95, 0x96, 0x1a, 0xe3, 0x18, 0xee, 0x50, 0x1c, 0xaa, 0x6f, 0x89, 0xa6,
	0xe8, 0x23, 0x85, 0x8a, 0x74, 0x29, 0x6c, 0x97, 0x66, 0x3f, 0x2c, 0x78, 0xf8, 0x3a, 0xd4, 0x62,
	0xc3, 0xf5, 0x9f, 0xda, 0x92, 0x16, 0x0f, 0x96, 0xb6, 0x14, 0x08, 0x7d, 0xb8, 0xc5, 0xb5, 0xa6,
	0x54, 0x73, 0x2d, 0x64, 0x5c, 0x0a, 0x6a, 0x53, 0xb9, 0x19, 0xa9, 0x58, 0xc4, 0x5c, 0x67, 0x8a,
	0x4a, 0x35, 0x0d, 0xc1, 0xbe, 0x80, 0xd7, 0x25, 0xa3, 0xd7, 0x0f, 0x0f, 0xaa, 0xb6, 0x46, 0x46,
	0x89, 0x13, 0xd4, 0x18, 0x2f, 0x00, 0xc4, 0x3a, 0x91, 0x4a, 0xb7, 0xbc, 0x69, 0x31, 0xec, 0x39,
	0xdc, 0x9d, 0xcc, 0xe7, 0xa4, 0x3e, 0x64, 0x52, 0x53, 0xef, 0xa7, 0xb2, 0x6b, 0xc0, 0x76, 0xda,
	0x5f, 0xb4, 0x66, 0x04, 0x76, 0x2c, 0xe3, 0x90, 0x4c, 0xed, 0x61, 0x50, 0x00, 0xb6, 0x80, 0x7b,
	0x53, 0x25, 0x37, 0x22, 0xa2, 0xc3, 0x85, 0xff, 0xdb, 0xcb, 0xb7, 0x30, 0xda, 0x2e, 0xf4, 0x2f,
	0x2e, 0xbe, 0xfc, 0x75, 0x04, 0xce, 0xe7, 0x72, 0x73, 0xf0, 0x13, 0xdc, 0xde, 0x1e, 0x55, 0x7c,
	0x72, 0x59, 0xaf, 0x59, 0xe7, 0x4a, 0x79, 0x7e, 0x7f, 0x42, 0xa1, 0x87, 0xdd, 0x40, 0x0e, 0xb8,
	0xdf, 0x75, 0x7c, 0xda, 0xdc, 0xec, 0x1d, 0x4d, 0xef, 0xd9, 0xe1, 0xa4, 0xba, 0xc4, 0x3b, 0x80,
	0xa6, 0x8b, 0xf8, 0xa8, 0xb9, 0xb5, 0x37, 0x02, 0xde, 0x79, 0xf7, 0x61, 0xfd, 0xd4, 0x04, 0x4e,
	0xda, 0xbe, 0xe2, 0xe3, 0x26, 0xbf, 0xa3, 0xb1, 0xde, 0x45, 0xdf, 0x71, 0xf5, 0xe0, 0xec, 0xd8,
	0xfc, 0xa0, 0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x24, 0x78, 0x11, 0xbb, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifierClient interface {
	MakeCredential(ctx context.Context, in *MakeCredentialRequest, opts ...grpc.CallOption) (*MakeCredentialResponse, error)
	ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error)
	OfferQuote(ctx context.Context, in *OfferQuoteRequest, opts ...grpc.CallOption) (*OfferQuoteResponse, error)
	ProvideQuote(ctx context.Context, in *ProvideQuoteRequest, opts ...grpc.CallOption) (*ProvideQuoteResponse, error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) MakeCredential(ctx context.Context, in *MakeCredentialRequest, opts ...grpc.CallOption) (*MakeCredentialResponse, error) {
	out := new(MakeCredentialResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/MakeCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error) {
	out := new(ActivateCredentialResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/ActivateCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferQuote(ctx context.Context, in *OfferQuoteRequest, opts ...grpc.CallOption) (*OfferQuoteResponse, error) {
	out := new(OfferQuoteResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/OfferQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ProvideQuote(ctx context.Context, in *ProvideQuoteRequest, opts ...grpc.CallOption) (*ProvideQuoteResponse, error) {
	out := new(ProvideQuoteResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/ProvideQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
type VerifierServer interface {
	MakeCredential(context.Context, *MakeCredentialRequest) (*MakeCredentialResponse, error)
	ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error)
	OfferQuote(context.Context, *OfferQuoteRequest) (*OfferQuoteResponse, error)
	ProvideQuote(context.Context, *ProvideQuoteRequest) (*ProvideQuoteResponse, error)
}

// UnimplementedVerifierServer can be embedded to have forward compatible implementations.
type UnimplementedVerifierServer struct {
}

func (*UnimplementedVerifierServer) MakeCredential(ctx context.Context, req *MakeCredentialRequest) (*MakeCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeCredential not implemented")
}
func (*UnimplementedVerifierServer) ActivateCredential(ctx context.Context, req *ActivateCredentialRequest) (*ActivateCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateCredential not implemented")
}
func (*UnimplementedVerifierServer) OfferQuote(ctx context.Context, req *OfferQuoteRequest) (*OfferQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferQuote not implemented")
}
func (*UnimplementedVerifierServer) ProvideQuote(ctx context.Context, req *ProvideQuoteRequest) (*ProvideQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvideQuote not implemented")
}

func RegisterVerifierServer(s *grpc.Server, srv VerifierServer) {
	s.RegisterService(&_Verifier_serviceDesc, srv)
}

func _Verifier_MakeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).MakeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/MakeCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).MakeCredential(ctx, req.(*MakeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ActivateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ActivateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/ActivateCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ActivateCredential(ctx, req.(*ActivateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/OfferQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferQuote(ctx, req.(*OfferQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ProvideQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ProvideQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/ProvideQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ProvideQuote(ctx, req.(*ProvideQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Verifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "verifier.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeCredential",
			Handler:    _Verifier_MakeCredential_Handler,
		},
		{
			MethodName: "ActivateCredential",
			Handler:    _Verifier_ActivateCredential_Handler,
		},
		{
			MethodName: "OfferQuote",
			Handler:    _Verifier_OfferQuote_Handler,
		},
		{
			MethodName: "ProvideQuote",
			Handler:    _Verifier_ProvideQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verifier/verifier.proto",
}
